import type { Component } from '@/types'

const NOW = 0 // static seed timestamp

export const ATOM_DEFINITIONS: Component[] = [
  {
    id: 'button',
    name: 'Button',
    atomicLevel: 'atom',
    description: 'A clickable element that triggers an action. The most fundamental interactive component in any design system.',
    usageGuidelines: 'Use primary buttons for the main call-to-action on a page. Limit to one primary button per section. Use secondary or ghost for supporting actions. Always include a visible label unless the context is unambiguous.',
    parts: [
      { id: 'container', name: 'Container', description: 'The outer clickable area' },
      { id: 'label', name: 'Label', description: 'The button text' },
      { id: 'icon-leading', name: 'Leading Icon', description: 'Optional icon before the label' },
      { id: 'icon-trailing', name: 'Trailing Icon', description: 'Optional icon after the label' },
      { id: 'spinner', name: 'Spinner', description: 'Loading indicator (loading state only)' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'pressed', name: 'Pressed' },
      { id: 'disabled', name: 'Disabled' },
      { id: 'loading', name: 'Loading' },
    ],
    variants: [
      { id: 'primary', name: 'Primary', category: 'appearance' },
      { id: 'secondary', name: 'Secondary', category: 'appearance' },
      { id: 'ghost', name: 'Ghost', category: 'appearance' },
      { id: 'destructive', name: 'Destructive', category: 'appearance' },
      { id: 'size-sm', name: 'Small', category: 'size' },
      { id: 'size-md', name: 'Medium', category: 'size' },
      { id: 'size-lg', name: 'Large', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'button-icon',
    name: 'Icon Button',
    atomicLevel: 'atom',
    description: 'A square button containing only an icon. Used when space is limited or the icon alone is sufficient to communicate the action.',
    usageGuidelines: 'Always provide an accessible label (aria-label) even when no text is shown. Use tooltips to reveal the action on hover. Prefer labeled buttons when the action may be unclear.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'icon', name: 'Icon' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'pressed', name: 'Pressed' },
      { id: 'disabled', name: 'Disabled' },
    ],
    variants: [
      { id: 'ghost', name: 'Ghost', category: 'appearance' },
      { id: 'filled', name: 'Filled', category: 'appearance' },
      { id: 'outlined', name: 'Outlined', category: 'appearance' },
      { id: 'size-sm', name: 'Small', category: 'size' },
      { id: 'size-md', name: 'Medium', category: 'size' },
      { id: 'size-lg', name: 'Large', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'input-text',
    name: 'Text Input',
    atomicLevel: 'atom',
    description: 'A single-line text entry field. Used for short-form user input like names, emails, and search queries.',
    usageGuidelines: 'Always pair with a visible label above the field. Use helper text to clarify format requirements. Show error messages below the field, replacing helper text. Never use placeholder text as a substitute for a label.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'label', name: 'Label' },
      { id: 'input-field', name: 'Input Field', description: 'The text entry area' },
      { id: 'placeholder', name: 'Placeholder' },
      { id: 'helper-text', name: 'Helper Text' },
      { id: 'error-text', name: 'Error Text' },
      { id: 'icon-leading', name: 'Leading Icon' },
      { id: 'icon-trailing', name: 'Trailing Icon' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'focus', name: 'Focus' },
      { id: 'filled', name: 'Filled' },
      { id: 'disabled', name: 'Disabled' },
      { id: 'error', name: 'Error' },
    ],
    variants: [
      { id: 'outlined', name: 'Outlined', category: 'appearance' },
      { id: 'filled', name: 'Filled', category: 'appearance' },
      { id: 'underline', name: 'Underline', category: 'appearance' },
      { id: 'size-sm', name: 'Small', category: 'size' },
      { id: 'size-md', name: 'Medium', category: 'size' },
      { id: 'size-lg', name: 'Large', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'input-select',
    name: 'Select',
    atomicLevel: 'atom',
    description: 'A dropdown selector for choosing one option from a predefined list.',
    usageGuidelines: 'Use when there are 5 or more options and radio buttons would be too verbose. Always show a default placeholder. Sort options logically — alphabetically, numerically, or by frequency of use.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'label', name: 'Label' },
      { id: 'value', name: 'Selected Value' },
      { id: 'icon-trailing', name: 'Trailing Icon', description: 'Chevron/arrow indicator' },
      { id: 'helper-text', name: 'Helper Text' },
      { id: 'error-text', name: 'Error Text' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'focus', name: 'Focus' },
      { id: 'open', name: 'Open' },
      { id: 'disabled', name: 'Disabled' },
      { id: 'error', name: 'Error' },
    ],
    variants: [
      { id: 'outlined', name: 'Outlined', category: 'appearance' },
      { id: 'filled', name: 'Filled', category: 'appearance' },
      { id: 'size-sm', name: 'Small', category: 'size' },
      { id: 'size-md', name: 'Medium', category: 'size' },
      { id: 'size-lg', name: 'Large', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    atomicLevel: 'atom',
    description: 'A binary toggle for selecting or deselecting an option. Supports indeterminate state for parent-child selection groups.',
    usageGuidelines: 'Use for multi-select scenarios. Group related checkboxes vertically with consistent spacing. Use indeterminate state only when a parent checkbox represents a mixed state of children.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'indicator', name: 'Indicator', description: 'The checkbox box and checkmark' },
      { id: 'label', name: 'Label' },
      { id: 'description', name: 'Description', description: 'Optional supporting text' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'checked', name: 'Checked' },
      { id: 'indeterminate', name: 'Indeterminate' },
      { id: 'disabled', name: 'Disabled' },
    ],
    variants: [],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'radio',
    name: 'Radio',
    atomicLevel: 'atom',
    description: 'A single-select option within a mutually exclusive group.',
    usageGuidelines: 'Always group radios in a fieldset with a shared legend. Use when there are 2-5 mutually exclusive options visible at once. For more options, prefer a select dropdown.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'indicator', name: 'Indicator', description: 'The radio circle and fill' },
      { id: 'label', name: 'Label' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'selected', name: 'Selected' },
      { id: 'disabled', name: 'Disabled' },
    ],
    variants: [],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'badge',
    name: 'Badge',
    atomicLevel: 'atom',
    description: 'A small label used to communicate status, category, or count. Non-interactive.',
    usageGuidelines: 'Keep badge text short — ideally one or two words. Use semantic color variants to reinforce meaning (green = success, red = error). Do not use badges for interactive actions; use tags instead.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'label', name: 'Label' },
    ],
    states: [
      { id: 'default', name: 'Default' },
    ],
    variants: [
      { id: 'primary', name: 'Primary', category: 'appearance' },
      { id: 'success', name: 'Success', category: 'appearance' },
      { id: 'warning', name: 'Warning', category: 'appearance' },
      { id: 'error', name: 'Error', category: 'appearance' },
      { id: 'neutral', name: 'Neutral', category: 'appearance' },
      { id: 'size-sm', name: 'Small', category: 'size' },
      { id: 'size-md', name: 'Medium', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'badge-dot',
    name: 'Badge Dot',
    atomicLevel: 'atom',
    description: 'A minimal dot indicator used to signal status without text. Commonly used for notification indicators and presence/availability.',
    usageGuidelines: 'Use only when the meaning is unambiguous in context (e.g. an avatar with an online dot). Avoid using dots as the sole indicator of critical states — always provide an accessible text alternative.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'dot', name: 'Dot' },
    ],
    states: [
      { id: 'default', name: 'Default' },
    ],
    variants: [
      { id: 'primary', name: 'Primary', category: 'appearance' },
      { id: 'success', name: 'Success', category: 'appearance' },
      { id: 'warning', name: 'Warning', category: 'appearance' },
      { id: 'error', name: 'Error', category: 'appearance' },
      { id: 'neutral', name: 'Neutral', category: 'appearance' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tag',
    name: 'Tag',
    atomicLevel: 'atom',
    description: 'An interactive label used for filtering, categorizing, or multi-value input. Can be selected or dismissed.',
    usageGuidelines: 'Use tags when users need to interact with labels (select, remove). Use badges for non-interactive labels. Keep tag text short. When used in a multi-select input, ensure keyboard navigation works correctly.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'label', name: 'Label' },
      { id: 'icon-leading', name: 'Leading Icon' },
      { id: 'icon-trailing', name: 'Trailing Icon', description: 'Often a remove/close icon' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'selected', name: 'Selected' },
      { id: 'disabled', name: 'Disabled' },
    ],
    variants: [
      { id: 'filled', name: 'Filled', category: 'appearance' },
      { id: 'outlined', name: 'Outlined', category: 'appearance' },
      { id: 'size-sm', name: 'Small', category: 'size' },
      { id: 'size-md', name: 'Medium', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'link',
    name: 'Link',
    atomicLevel: 'atom',
    description: 'A text hyperlink for navigation. Can appear inline within body text or as a standalone element.',
    usageGuidelines: 'Link text should describe the destination, not the action (use "View pricing" not "Click here"). Visited state helps users track navigation history. External links should open in a new tab with a visual indicator.',
    parts: [
      { id: 'text', name: 'Text' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'visited', name: 'Visited' },
      { id: 'active', name: 'Active' },
      { id: 'disabled', name: 'Disabled' },
    ],
    variants: [
      { id: 'inline', name: 'Inline', category: 'type' },
      { id: 'standalone', name: 'Standalone', category: 'type' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'avatar',
    name: 'Avatar',
    atomicLevel: 'atom',
    description: 'A visual representation of a user or entity. Shows a photo, initials, or a fallback icon.',
    usageGuidelines: 'Always provide an alt text or accessible label. When showing initials, use 1-2 characters. Stack avatars with consistent overlap and ensure each has a visible border against varied backgrounds.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'image', name: 'Image' },
      { id: 'initials', name: 'Initials', description: 'Fallback text when no image' },
      { id: 'indicator', name: 'Indicator', description: 'Optional status dot' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'loading', name: 'Loading' },
    ],
    variants: [
      { id: 'size-sm', name: 'Small (24px)', category: 'size' },
      { id: 'size-md', name: 'Medium (32px)', category: 'size' },
      { id: 'size-lg', name: 'Large (40px)', category: 'size' },
      { id: 'size-xl', name: 'Extra Large (56px)', category: 'size' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'divider',
    name: 'Divider',
    atomicLevel: 'atom',
    description: 'A visual separator between sections or list items. Can be horizontal or vertical, with or without a label.',
    usageGuidelines: 'Use sparingly. Whitespace often communicates separation more elegantly than a divider. Use labeled dividers to introduce new sections in long forms or settings panels.',
    parts: [
      { id: 'line', name: 'Line' },
      { id: 'label', name: 'Label', description: 'Optional center text' },
    ],
    states: [
      { id: 'default', name: 'Default' },
    ],
    variants: [
      { id: 'horizontal', name: 'Horizontal', category: 'type' },
      { id: 'vertical', name: 'Vertical', category: 'type' },
      { id: 'no-label', name: 'No Label', category: 'type' },
      { id: 'with-label', name: 'With Label', category: 'type' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'card',
    name: 'Card',
    atomicLevel: 'molecule',
    description: 'A contained surface for grouping related content. Can be flat, elevated, or outlined.',
    usageGuidelines: 'Use cards to group related items into scannable units. Keep card content focused on a single topic. Avoid nesting cards inside cards. Interactive cards should have a clear hover/focus state.',
    parts: [
      { id: 'container', name: 'Container' },
      { id: 'header', name: 'Header' },
      { id: 'body', name: 'Body' },
      { id: 'footer', name: 'Footer' },
    ],
    states: [
      { id: 'default', name: 'Default' },
      { id: 'hover', name: 'Hover' },
      { id: 'selected', name: 'Selected' },
    ],
    variants: [
      { id: 'flat', name: 'Flat', category: 'appearance' },
      { id: 'elevated', name: 'Elevated', category: 'appearance' },
      { id: 'outlined', name: 'Outlined', category: 'appearance' },
    ],
    bindings: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
]
