import type { ResolvedTokenMap, CompilationOptions } from '@/types'

/**
 * Convert a token path to CSS custom property name
 * Example: "color.semantic.primary" -> "--color-semantic-primary"
 */
function tokenPathToCSSVar(path: string, prefix?: string): string {
  const kebabCase = path.replace(/\./g, '-')
  return prefix ? `--${prefix}-${kebabCase}` : `--${kebabCase}`
}

/**
 * Compile resolved tokens to CSS custom properties
 */
export function compileToCss(
  tokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    prefix = '',
    includeComments = true,
    prettify = true,
  } = options

  const indent = prettify ? '  ' : ''
  const newline = prettify ? '\n' : ''
  const space = prettify ? ' ' : ''

  let css = ''

  // Header comment
  if (includeComments) {
    css += `/**${newline}`
    css += ` * Design Tokens - CSS Custom Properties${newline}`
    css += ` * Generated by Design Token Compiler${newline}`
    css += ` * ${new Date().toISOString()}${newline}`
    css += ` */${newline}${newline}`
  }

  // :root block
  css += `:root${space}{${newline}`

  // Sort tokens by path for consistent output
  const sortedPaths = Object.keys(tokens).sort()

  // Group tokens by top-level category for better organization
  const categories: Record<string, string[]> = {}
  sortedPaths.forEach((path) => {
    const category = path.split('.')[0]
    if (!categories[category]) {
      categories[category] = []
    }
    categories[category].push(path)
  })

  // Generate CSS variables
  Object.entries(categories).forEach(([category, paths], index) => {
    // Add category comment
    if (includeComments && prettify) {
      if (index > 0) css += newline
      css += `${indent}/* ${category.charAt(0).toUpperCase() + category.slice(1)} */${newline}`
    }

    paths.forEach((path) => {
      const token = tokens[path]
      const varName = tokenPathToCSSVar(path, prefix)
      const value = token.resolvedValue

      // Add token description as comment
      if (includeComments && token.description && prettify) {
        css += `${indent}/* ${token.description} */${newline}`
      }

      css += `${indent}${varName}:${space}${value};${newline}`
    })
  })

  css += `}${newline}`

  return css
}

/**
 * Compile tokens with dark mode support
 * Generates both :root and [data-theme="dark"] blocks
 */
export function compileToCssWithModes(
  lightTokens: ResolvedTokenMap,
  darkTokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    prefix = '',
    includeComments = true,
    prettify = true,
  } = options

  const indent = prettify ? '  ' : ''
  const newline = prettify ? '\n' : ''
  const space = prettify ? ' ' : ''

  let css = ''

  // Header comment
  if (includeComments) {
    css += `/**${newline}`
    css += ` * Design Tokens - CSS Custom Properties${newline}`
    css += ` * Generated by Design Token Compiler${newline}`
    css += ` * Includes light and dark mode support${newline}`
    css += ` * ${new Date().toISOString()}${newline}`
    css += ` */${newline}${newline}`
  }

  // Light mode (default)
  css += `:root,${newline}`
  css += `[data-theme="light"]${space}{${newline}`

  const lightPaths = Object.keys(lightTokens).sort()
  lightPaths.forEach((path) => {
    const token = lightTokens[path]
    const varName = tokenPathToCSSVar(path, prefix)
    const value = token.resolvedValue

    if (includeComments && token.description && prettify) {
      css += `${indent}/* ${token.description} */${newline}`
    }

    css += `${indent}${varName}:${space}${value};${newline}`
  })

  css += `}${newline}${newline}`

  // Dark mode
  css += `[data-theme="dark"]${space}{${newline}`

  // Only include tokens that are different in dark mode
  const darkPaths = Object.keys(darkTokens).sort()
  const overriddenTokens = darkPaths.filter((path) => {
    const darkValue = darkTokens[path].resolvedValue
    const lightValue = lightTokens[path]?.resolvedValue
    return darkValue !== lightValue
  })

  if (includeComments && prettify) {
    css += `${indent}/* Dark mode overrides */${newline}`
  }

  overriddenTokens.forEach((path) => {
    const token = darkTokens[path]
    const varName = tokenPathToCSSVar(path, prefix)
    const value = token.resolvedValue

    css += `${indent}${varName}:${space}${value};${newline}`
  })

  css += `}${newline}`

  return css
}
