import type { ResolvedTokenMap, CompilationOptions } from '@/types'

/**
 * Convert a token path to SCSS variable name
 * Example: "color.semantic.primary" -> "$color-semantic-primary"
 */
function tokenPathToScssVar(path: string, prefix?: string): string {
  const kebabCase = path.replace(/\./g, '-')
  return prefix ? `$${prefix}-${kebabCase}` : `$${kebabCase}`
}

/**
 * Compile resolved tokens to SCSS variables
 */
export function compileToScss(
  tokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    prefix = '',
    includeComments = true,
    prettify = true,
  } = options

  const newline = prettify ? '\n' : ''

  let scss = ''

  // Header comment
  if (includeComments) {
    scss += `//\n`
    scss += `// Design Tokens - SCSS Variables\n`
    scss += `// Generated by Design Token Compiler\n`
    scss += `// ${new Date().toISOString()}\n`
    scss += `//\n${newline}`
  }

  // Sort tokens by path for consistent output
  const sortedPaths = Object.keys(tokens).sort()

  // Group tokens by top-level category for better organization
  const categories: Record<string, string[]> = {}
  sortedPaths.forEach((path) => {
    const category = path.split('.')[0]
    if (!categories[category]) {
      categories[category] = []
    }
    categories[category].push(path)
  })

  // Generate SCSS variables
  Object.entries(categories).forEach(([category, paths], index) => {
    // Add category comment
    if (includeComments && prettify) {
      if (index > 0) scss += newline
      scss += `// ${category.charAt(0).toUpperCase() + category.slice(1)}${newline}`
    }

    paths.forEach((path) => {
      const token = tokens[path]
      const varName = tokenPathToScssVar(path, prefix)
      const value = token.resolvedValue

      // Add token description as comment
      if (includeComments && token.description && prettify) {
        scss += `// ${token.description}${newline}`
      }

      scss += `${varName}: ${value};${newline}`
    })
  })

  return scss
}

/**
 * Compile tokens with dark mode support
 * Generates both default variables and a dark mode map
 */
export function compileToScssWithModes(
  lightTokens: ResolvedTokenMap,
  darkTokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    prefix = '',
    includeComments = true,
    prettify = true,
  } = options

  const newline = prettify ? '\n' : ''
  const indent = prettify ? '  ' : ''

  let scss = ''

  // Header comment
  if (includeComments) {
    scss += `//\n`
    scss += `// Design Tokens - SCSS Variables\n`
    scss += `// Generated by Design Token Compiler\n`
    scss += `// Includes light and dark mode support\n`
    scss += `// ${new Date().toISOString()}\n`
    scss += `//\n${newline}`
  }

  // Light mode variables (default)
  if (includeComments) {
    scss += `// Light mode (default)${newline}`
  }

  const lightPaths = Object.keys(lightTokens).sort()
  lightPaths.forEach((path) => {
    const token = lightTokens[path]
    const varName = tokenPathToScssVar(path, prefix)
    const value = token.resolvedValue

    if (includeComments && token.description && prettify) {
      scss += `// ${token.description}${newline}`
    }

    scss += `${varName}: ${value};${newline}`
  })

  scss += newline

  // Dark mode as a map
  if (includeComments) {
    scss += `// Dark mode overrides${newline}`
  }

  scss += `$dark-mode-tokens: (${newline}`

  // Only include tokens that are different in dark mode
  const darkPaths = Object.keys(darkTokens).sort()
  const overriddenTokens = darkPaths.filter((path) => {
    const darkValue = darkTokens[path].resolvedValue
    const lightValue = lightTokens[path]?.resolvedValue
    return darkValue !== lightValue
  })

  overriddenTokens.forEach((path, index) => {
    const token = darkTokens[path]
    const key = path.replace(/\./g, '-')
    const value = token.resolvedValue

    scss += `${indent}'${key}': ${value}`

    if (index < overriddenTokens.length - 1) {
      scss += `,${newline}`
    } else {
      scss += newline
    }
  })

  scss += `);${newline}${newline}`

  // Helper mixin for applying dark mode
  if (includeComments) {
    scss += `// Mixin to apply dark mode${newline}`
    scss += `// Usage: @include dark-mode { ... }${newline}`
  }

  scss += `@mixin dark-mode {${newline}`
  scss += `${indent}[data-theme="dark"] & {${newline}`
  scss += `${indent}${indent}@content;${newline}`
  scss += `${indent}}${newline}`
  scss += `}${newline}`

  return scss
}
