import type { ResolvedTokenMap, CompilationOptions } from '@/types'

/**
 * Convert token path to Tailwind config key
 * Example: "color.semantic.primary" -> primary (in colors.semantic)
 */
function tokenPathToTailwindPath(path: string): { category: string; key: string } {
  const parts = path.split('.')
  if (parts.length < 2) {
    return { category: parts[0], key: 'DEFAULT' }
  }

  const category = parts[0]
  const key = parts.slice(1).join('-')
  return { category, key }
}

/**
 * Build nested Tailwind theme config from tokens
 */
function buildTailwindTheme(tokens: ResolvedTokenMap): Record<string, unknown> {
  const theme: Record<string, Record<string, unknown>> = {
    colors: {},
    spacing: {},
    borderRadius: {},
    fontSize: {},
    fontWeight: {},
    lineHeight: {},
    letterSpacing: {},
    boxShadow: {},
    opacity: {},
    zIndex: {},
    transitionDuration: {},
    transitionTimingFunction: {},
  }

  Object.entries(tokens).forEach(([path, token]) => {
    const { category, key } = tokenPathToTailwindPath(path)
    const value = token.resolvedValue

    // Map token categories to Tailwind config keys
    if (category === 'color') {
      theme.colors[key] = value
    } else if (category === 'spacing') {
      theme.spacing[key] = value
    } else if (category === 'borderRadius') {
      theme.borderRadius[key] = value
    } else if (category === 'fontSize') {
      theme.fontSize[key] = value
    } else if (category === 'fontWeight') {
      theme.fontWeight[key] = value
    } else if (category === 'lineHeight') {
      theme.lineHeight[key] = value
    } else if (category === 'letterSpacing') {
      theme.letterSpacing[key] = value
    } else if (category === 'shadow') {
      theme.boxShadow[key] = value
    } else if (category === 'opacity') {
      theme.opacity[key] = value
    } else if (category === 'zIndex') {
      theme.zIndex[key] = value
    } else if (category === 'duration') {
      theme.transitionDuration[key] = value
    } else if (category === 'easing') {
      theme.transitionTimingFunction[key] = value
    }
  })

  // Remove empty categories
  Object.keys(theme).forEach((key) => {
    if (Object.keys(theme[key]).length === 0) {
      delete theme[key]
    }
  })

  return theme
}

/**
 * Convert object to JavaScript code string
 */
function objectToJavaScript(
  obj: Record<string, unknown>,
  indent = 0,
  prettify = true
): string {
  const indentStr = prettify ? '  '.repeat(indent) : ''
  const newline = prettify ? '\n' : ''
  const space = prettify ? ' ' : ''

  const entries = Object.entries(obj)
  if (entries.length === 0) return '{}'

  let result = `{${newline}`

  entries.forEach(([key, value], index) => {
    const needsQuotes = /[^a-zA-Z0-9_$]/.test(key) || /^[0-9]/.test(key)
    const keyStr = needsQuotes ? `'${key}'` : key

    result += `${indentStr}  ${keyStr}:${space}`

    if (value && typeof value === 'object' && !Array.isArray(value)) {
      result += objectToJavaScript(value as Record<string, unknown>, indent + 1, prettify)
    } else if (typeof value === 'string') {
      result += `'${value.replace(/'/g, "\\'")}'`
    } else {
      result += String(value)
    }

    if (index < entries.length - 1) {
      result += `,${newline}`
    } else {
      result += newline
    }
  })

  result += `${indentStr}}`

  return result
}

/**
 * Compile resolved tokens to Tailwind CSS config
 */
export function compileToTailwind(
  tokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    includeComments = true,
    prettify = true,
  } = options

  const newline = prettify ? '\n' : ''

  let config = ''

  // Header comment
  if (includeComments) {
    config += `/**${newline}`
    config += ` * Design Tokens - Tailwind CSS Config${newline}`
    config += ` * Generated by Design Token Compiler${newline}`
    config += ` * ${new Date().toISOString()}${newline}`
    config += ` */${newline}${newline}`
  }

  // Build theme object
  const theme = buildTailwindTheme(tokens)

  // Generate config
  config += `/** @type {import('tailwindcss').Config} */${newline}`
  config += `module.exports = ${objectToJavaScript({
    theme: {
      extend: theme,
    },
  }, 0, prettify)}${newline}`

  return config
}

/**
 * Compile tokens with dark mode support
 */
export function compileToTailwindWithModes(
  lightTokens: ResolvedTokenMap,
  darkTokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    includeComments = true,
    prettify = true,
  } = options

  const newline = prettify ? '\n' : ''

  let config = ''

  // Header comment
  if (includeComments) {
    config += `/**${newline}`
    config += ` * Design Tokens - Tailwind CSS Config${newline}`
    config += ` * Generated by Design Token Compiler${newline}`
    config += ` * Includes dark mode support${newline}`
    config += ` * ${new Date().toISOString()}${newline}`
    config += ` */${newline}${newline}`
  }

  // Build theme objects
  const lightTheme = buildTailwindTheme(lightTokens)

  // Note: Tailwind handles dark mode via class or media query
  // We'll use the light theme as the base
  config += `/** @type {import('tailwindcss').Config} */${newline}`
  config += `module.exports = ${objectToJavaScript({
    darkMode: 'class', // or 'media'
    theme: {
      extend: lightTheme,
    },
  }, 0, prettify)}${newline}`

  if (includeComments) {
    config += `${newline}// Note: Dark mode tokens should be applied via Tailwind's dark: modifier${newline}`
    config += `// Example: <div class="bg-background dark:bg-gray-900">${newline}`
  }

  return config
}
