import type { ResolvedTokenMap, CompilationOptions } from '@/types'

/**
 * Convert a token path to TypeScript property path
 * Example: "color.semantic.primary" -> "color.semantic.primary"
 */
function tokenPathToTsPath(path: string): string {
  return path
}

/**
 * Escape string values for TypeScript
 */
function escapeStringValue(value: unknown): string {
  if (typeof value === 'string') {
    return `'${value.replace(/'/g, "\\'")}'`
  }
  return String(value)
}

/**
 * Build nested object structure from flat token paths
 */
function buildNestedObject(tokens: ResolvedTokenMap): Record<string, unknown> {
  const result: Record<string, unknown> = {}

  Object.entries(tokens).forEach(([path, token]) => {
    const parts = path.split('.')
    let current: Record<string, unknown> = result

    parts.forEach((part, index) => {
      if (index === parts.length - 1) {
        // Last part: assign the value
        current[part] = token.resolvedValue
      } else {
        // Create nested object if it doesn't exist
        if (!current[part] || typeof current[part] !== 'object') {
          current[part] = {}
        }
        current = current[part] as Record<string, unknown>
      }
    })
  })

  return result
}

/**
 * Convert object to TypeScript code string
 */
function objectToTypeScript(
  obj: Record<string, unknown>,
  indent = 0,
  prettify = true
): string {
  const indentStr = prettify ? '  '.repeat(indent) : ''
  const newline = prettify ? '\n' : ''
  const space = prettify ? ' ' : ''

  const entries = Object.entries(obj)
  if (entries.length === 0) return '{}'

  let result = `{${newline}`

  entries.forEach(([key, value], index) => {
    const needsQuotes = /[^a-zA-Z0-9_$]/.test(key) || /^[0-9]/.test(key)
    const keyStr = needsQuotes ? `'${key}'` : key

    result += `${indentStr}  ${keyStr}:${space}`

    if (value && typeof value === 'object' && !Array.isArray(value)) {
      result += objectToTypeScript(value as Record<string, unknown>, indent + 1, prettify)
    } else {
      result += escapeStringValue(value)
    }

    if (index < entries.length - 1) {
      result += `,${newline}`
    } else {
      result += newline
    }
  })

  result += `${indentStr}}`

  return result
}

/**
 * Compile resolved tokens to TypeScript module
 */
export function compileToTypeScript(
  tokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    includeComments = true,
    prettify = true,
  } = options

  const newline = prettify ? '\n' : ''

  let ts = ''

  // Header comment
  if (includeComments) {
    ts += `/**${newline}`
    ts += ` * Design Tokens - TypeScript Module${newline}`
    ts += ` * Generated by Design Token Compiler${newline}`
    ts += ` * ${new Date().toISOString()}${newline}`
    ts += ` */${newline}${newline}`
  }

  // Build nested object
  const nested = buildNestedObject(tokens)

  // Export as const for type inference
  ts += `export const tokens = ${objectToTypeScript(nested, 0, prettify)} as const${newline}${newline}`

  // Export type for autocomplete
  ts += `export type Tokens = typeof tokens${newline}${newline}`

  // Export helper function to get token values
  if (includeComments) {
    ts += `/**${newline}`
    ts += ` * Get a token value by path${newline}`
    ts += ` * Example: getToken('color', 'semantic', 'primary')${newline}`
    ts += ` */${newline}`
  }
  ts += `export function getToken(...path: string[]): string {${newline}`
  ts += `  let value: any = tokens${newline}`
  ts += `  for (const key of path) {${newline}`
  ts += `    value = value[key]${newline}`
  ts += `    if (value === undefined) {${newline}`
  ts += `      throw new Error(\`Token not found: \${path.join('.')}\`)${newline}`
  ts += `    }${newline}`
  ts += `  }${newline}`
  ts += `  return String(value)${newline}`
  ts += `}${newline}`

  return ts
}

/**
 * Compile tokens with theme support
 */
export function compileToTypeScriptWithModes(
  lightTokens: ResolvedTokenMap,
  darkTokens: ResolvedTokenMap,
  options: CompilationOptions = {}
): string {
  const {
    includeComments = true,
    prettify = true,
  } = options

  const newline = prettify ? '\n' : ''

  let ts = ''

  // Header comment
  if (includeComments) {
    ts += `/**${newline}`
    ts += ` * Design Tokens - TypeScript Module${newline}`
    ts += ` * Generated by Design Token Compiler${newline}`
    ts += ` * Includes light and dark theme support${newline}`
    ts += ` * ${new Date().toISOString()}${newline}`
    ts += ` */${newline}${newline}`
  }

  // Build nested objects
  const lightNested = buildNestedObject(lightTokens)
  const darkNested = buildNestedObject(darkTokens)

  // Export themes
  ts += `export const themes = {${newline}`
  ts += `  light: ${objectToTypeScript(lightNested, 1, prettify)},${newline}`
  ts += `  dark: ${objectToTypeScript(darkNested, 1, prettify)}${newline}`
  ts += `} as const${newline}${newline}`

  // Export types
  ts += `export type Theme = 'light' | 'dark'${newline}`
  ts += `export type Themes = typeof themes${newline}${newline}`

  // Export helper function
  if (includeComments) {
    ts += `/**${newline}`
    ts += ` * Get a token value by theme and path${newline}`
    ts += ` * Example: getToken('light', 'color', 'semantic', 'primary')${newline}`
    ts += ` */${newline}`
  }
  ts += `export function getToken(theme: Theme, ...path: string[]): string {${newline}`
  ts += `  let value: any = themes[theme]${newline}`
  ts += `  for (const key of path) {${newline}`
  ts += `    value = value[key]${newline}`
  ts += `    if (value === undefined) {${newline}`
  ts += `      throw new Error(\`Token not found: \${theme}.\${path.join('.')}\`)${newline}`
  ts += `    }${newline}`
  ts += `  }${newline}`
  ts += `  return String(value)${newline}`
  ts += `}${newline}`

  return ts
}
