import type { Component, ResolvedTokenMap } from '@/types'

function tokenPathToCssVar(tokenPath: string): string {
  return `--${tokenPath.replace(/\./g, '-')}`
}

export function compileWebReact(component: Component, resolvedTokens: ResolvedTokenMap): { tsx: string; css: string } {
  const id = component.id
  const name = id
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')

  // --- Generate TypeScript props interface ---
  const appearanceVariants = component.variants.filter((v) => v.category === 'appearance')
  const sizeVariants = component.variants.filter((v) => v.category === 'size')

  const variantProp = appearanceVariants.length > 0
    ? `  variant?: ${appearanceVariants.map((v) => `'${v.id}'`).join(' | ')}`
    : null
  const sizeProp = sizeVariants.length > 0
    ? `  size?: ${sizeVariants.map((v) => `'${v.id.replace('size-', '')}'`).join(' | ')}`
    : null

  const hasLabel = component.parts.some((p) => p.id === 'label' || p.id === 'text')
  const hasIconLeading = component.parts.some((p) => p.id === 'icon-leading')
  const hasIconTrailing = component.parts.some((p) => p.id === 'icon-trailing')
  const hasDisabled = component.states.some((s) => s.id === 'disabled')
  const hasChildren = hasLabel || ['button', 'button-icon'].includes(id)

  const props: string[] = []
  if (variantProp) props.push(variantProp)
  if (sizeProp) props.push(sizeProp)
  if (hasDisabled) props.push('  disabled?: boolean')
  if (hasIconLeading) props.push('  iconLeading?: React.ReactNode')
  if (hasIconTrailing) props.push('  iconTrailing?: React.ReactNode')
  if (hasChildren) props.push('  children?: React.ReactNode')
  props.push(`  className?: string`)

  const defaultVariant = appearanceVariants[0]?.id
  const defaultSize = sizeVariants.find((v) => v.id === 'size-md')?.id.replace('size-', '') || sizeVariants[0]?.id.replace('size-', '')

  const defaultProps: string[] = []
  if (defaultVariant) defaultProps.push(`variant = '${defaultVariant}'`)
  if (defaultSize) defaultProps.push(`size = '${defaultSize}'`)
  if (hasDisabled) defaultProps.push('disabled = false')

  const classNameParts: string[] = [`'${id}'`]
  if (appearanceVariants.length > 0) classNameParts.push('`${id}--${variant}`')
  if (sizeVariants.length > 0) classNameParts.push('`${id}--size-${size}`')
  classNameParts.push('className')

  const tsx = `import React from 'react'
import './${id}.css'

interface ${name}Props {
${props.join('\n')}
}

export const ${name}: React.FC<${name}Props> = ({
  ${defaultProps.join(',\n  ')}${defaultProps.length > 0 ? ',' : ''}
  ${hasIconLeading ? 'iconLeading,' : ''}
  ${hasIconTrailing ? 'iconTrailing,' : ''}
  ${hasChildren ? 'children,' : ''}
  className = '',
}) => {
  const classes = [${classNameParts.join(', ')}]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={classes}${hasDisabled ? ' aria-disabled={disabled}' : ''}>
      ${hasIconLeading ? `{iconLeading && <span className="${id}__icon-leading">{iconLeading}</span>}` : ''}
      ${hasLabel || hasChildren ? `{children && <span className="${id}__label">{children}</span>}` : ''}
      ${hasIconTrailing ? `{iconTrailing && <span className="${id}__icon-trailing">{iconTrailing}</span>}` : ''}
    </div>
  )
}

export default ${name}
`

  // --- Generate CSS ---
  const cssLines: string[] = [
    `/* ${name} component styles */`,
    `/* Generated by Token Compiler — do not edit manually */`,
    `/* Requires: your compiled token CSS file (tokens.css) */`,
    '',
    `.${id} {`,
  ]

  // Collect base (default state, no variant) bindings
  const baseBindings = component.bindings.filter((b) => b.stateId === 'default' && b.variantId === null)
  for (const b of baseBindings) {
    const cssVar = tokenPathToCssVar(b.tokenPath)
    cssLines.push(`  ${b.cssProperty}: var(${cssVar});`)
  }
  cssLines.push('}', '')

  // State-based rules
  const stateMap: Record<string, typeof component.bindings> = {}
  for (const b of component.bindings) {
    if (b.stateId === 'default') continue
    if (b.variantId !== null) continue
    if (!stateMap[b.stateId]) stateMap[b.stateId] = []
    stateMap[b.stateId].push(b)
  }

  const statePseudoMap: Record<string, string> = {
    hover: ':hover',
    pressed: ':active',
    focus: ':focus-visible',
    disabled: '[aria-disabled="true"]',
    error: '.is-error',
  }

  for (const [stateId, bindings] of Object.entries(stateMap)) {
    const pseudo = statePseudoMap[stateId] || `.is-${stateId}`
    cssLines.push(`.${id}${pseudo} {`)
    for (const b of bindings) {
      cssLines.push(`  ${b.cssProperty}: var(${tokenPathToCssVar(b.tokenPath)});`)
    }
    cssLines.push('}', '')
  }

  // Variant rules
  const variantMap: Record<string, typeof component.bindings> = {}
  for (const b of component.bindings) {
    if (!b.variantId) continue
    if (!variantMap[b.variantId]) variantMap[b.variantId] = []
    variantMap[b.variantId].push(b)
  }

  for (const [variantId, bindings] of Object.entries(variantMap)) {
    cssLines.push(`.${id}--${variantId} {`)
    for (const b of bindings) {
      cssLines.push(`  ${b.cssProperty}: var(${tokenPathToCssVar(b.tokenPath)});`)
    }
    cssLines.push('}', '')
  }

  return { tsx: tsx.trim(), css: cssLines.join('\n') }
}
